In [1]:
import sys 
from pathlib import Path

In [2]:
root_dir = Path.cwd().parent
sys.path.append(str(root_dir))

In [3]:
import numpy as np
import pandas as pd 
from src.data_loader import load_data_raw
from src.cleaning_process import check_same_dtypes, check_columns_name, concat_df, check_unique_values, overview_dataset, check_data_types, drop_columns, handle_whitespace, export_data, drop_duplicate_columns

### LOAD DATA

In [4]:
dataset_name = [
    "delay_4_6_CONDITION_PRODUCT_SUPPLIER", 
    "delay_7_9_CONDITION_PRODUCT_SUPPLIER", 
    "not_delay_4_6_CONDITION_PRODUCT_SUPPLIER", 
    "not_delay_7_9_CONDITION_PRODUCT_SUPPLIER"
]

In [5]:
delay_4_6 = load_data_raw(dataset_name[0])
not_delay_4_6 = load_data_raw(dataset_name[2])
delay_7_9 = load_data_raw(dataset_name[1])
not_delay_7_9 = load_data_raw(dataset_name[3])

### DATA UNIFICATION FOR DATASET APRIL TO JUNE

In [6]:
check_same_dtypes(delay_4_6, not_delay_4_6)

They are different about:
Column 'Consider count hodiday Saturday': int64 vs object

In [7]:
not_delay_4_6["Consider count hodiday Saturday"] = pd.to_numeric(not_delay_4_6["Consider count hodiday Saturday"], errors="coerce").fillna(0).astype("int64")

In [8]:
check_columns_name(delay_4_6, not_delay_4_6)

They have the same column names

In [9]:
df_4_6 = concat_df(delay_4_6, not_delay_4_6)

### OVERVIEW OF DATASET APRIL TO JUNE

In [10]:
overview_dataset(df_4_6, "April to June")

Overview of April to June:
Dataset shape: (399053, 47)
Number of columns: 47
Number of rows: 399053
Data overview of data April to June:,                  Order date SUBSIDIARY_CD     GLOBAL_NO   CLASSIFY_CD  \
count                399053        399053  3.990530e+05  3.990530e+05
unique                   78             1           NaN           NaN
top     2022-06-01 00:00:00           MJP           NaN           NaN
freq                   7293        399053           NaN           NaN
mean                    NaN           NaN  6.160898e+12  6.020041e+06
std                     NaN           NaN  3.664949e+12  6.373787e+06
min                     NaN           NaN  1.000047e+12  1.030101e+06
25%                     NaN           NaN  3.102610e+12  3.642508e+06
50%                     NaN           NaN  7.005071e+12  3.734125e+06
75%                     NaN           NaN  8.110474e+12  3.954111e+06
max                     NaN           NaN  3.252606e+13  9.901000e+07

              CUST_CD BRAND_CD     INNER_CD SUPPLIER_CD  \
count   399053.000000   399053       399053      399053
unique            NaN     1755       110113         877
top               NaN     MSM1  30350820001        0143
freq              NaN   348902        10992       36302
mean    246534.939607      NaN          NaN         NaN
std     255248.453768      NaN          NaN         NaN
min         22.000000      NaN          NaN         NaN
25%      48150.000000      NaN          NaN         NaN
50%     124302.000000      NaN          NaN         NaN
75%     411664.000000      NaN          NaN         NaN
max     999951.000000      NaN          NaN         NaN

        Sales order line number    Stock class  ...  SO_DAY_OF_MONTH  \
count             399053.000000  399053.000000  ...    399053.000000
unique                      NaN            NaN  ...              NaN
top                         NaN            NaN  ...              NaN
freq                        NaN            NaN  ...              NaN
mean                 107.772597       0.995186  ...        16.026816
std                 2853.767465       0.069215  ...         8.398729
min                    1.000000       0.000000  ...         1.000000
25%                    1.000000       1.000000  ...         9.000000
50%                    3.000000       1.000000  ...        16.000000
75%                   12.000000       1.000000  ...        23.000000
max                90025.000000       1.000000  ...        31.000000

        SO_DAY_OF_WEEK   IO_UNFIT_FLG  WEIGHT_UNIT  REASON_CD SOUF_RCV_NO  \
count    399053.000000  399053.000000       397176     399053       14842
unique             NaN            NaN            1         61       14819
top                NaN            NaN            g                 026257
freq               NaN            NaN       397176     378842           4
mean          3.063909       0.000015          NaN        NaN         NaN
std           1.479315       0.003878          NaN        NaN         NaN
min           1.000000       0.000000          NaN        NaN         NaN
25%           2.000000       0.000000          NaN        NaN         NaN
50%           3.000000       0.000000          NaN        NaN         NaN
75%           4.000000       0.000000          NaN        NaN         NaN
max           6.000000       1.000000          NaN        NaN         NaN

          QTUF_RCV_NO        SO_TIME  SUPPLIER_CATEGORY_CD  PRODUCT_ASSORT
count      593.000000  399053.000000         399053.000000          399053
unique            NaN            NaN                   NaN               1
top               NaN            NaN                   NaN
freq              NaN            NaN                   NaN          399053
mean    658580.016863  135193.173295              4.566947             NaN
std     388188.957813   30811.081333              0.826848             NaN
min        378.000000   73000.000000              2.000000             NaN
25%      82274.000000  110138.000000              5.000000             NaN
50%     861475.000000  140019.000000              5.000000             NaN
75%     935207.000000  161911.000000              5.000000             NaN
max     999634.000000  202951.000000              6.000000             NaN

[11 rows x 47 columns]

In [11]:
check_data_types(df_4_6, "April to June")

Data types in April to June:
Order date                          object
SUBSIDIARY_CD                       object
GLOBAL_NO                            int64
CLASSIFY_CD                          int64
CUST_CD                              int64
BRAND_CD                            object
INNER_CD                            object
SUPPLIER_CD                         object
Sales order line number              int64
Stock class                          int64
Consider count hodiday Saturday      int64
SO QTY                               int64
OTHER AREA SHIP DIV                 object
ALLOCATION QTY                       int64
SUPPLIER INV AMOUNT                float64
PACKING RANK                        object
PRODUCT_CD                          object
PRODUCT ATTRIBUTION                  int64
SPECIAL DIV                          int64
LOGICAL PLANT                        int64
PURCHASE AMOUNT                    float64
VSD                                 object
DIRECT SHIP FLG                      int64
DELI_DIV                            object
label                                int64
Ship Mode                           object
SHIP DECISION NO                   float64
PACK QTY                             int64
WEIGHT PER PIECE                     int64
SUPPLIER_DIV                       float64
HEAVY_FLG                            int64
EXPENSIVE_FLG                        int64
SPECIAL_DIV                          int64
ACTUAL_SHIP_DAYS                     int64
SPECIFY_PRODUCTION_DAYS              int64
SPECIFY_SHIP_DAYS                    int64
HAZARD_FLG                           int64
SO_DAY_OF_MONTH                      int64
SO_DAY_OF_WEEK                       int64
IO_UNFIT_FLG                         int64
WEIGHT_UNIT                         object
REASON_CD                           object
SOUF_RCV_NO                         object
QTUF_RCV_NO                        float64
SO_TIME                              int64
SUPPLIER_CATEGORY_CD                 int64
PRODUCT_ASSORT                      object
dtype: object

In [12]:
check_unique_values(df_4_6, "April to June")

Unique values in April to June:
Order date                             78
SUBSIDIARY_CD                           1
GLOBAL_NO                          399053
CLASSIFY_CD                          4106
CUST_CD                             39071
BRAND_CD                             1755
INNER_CD                           110113
SUPPLIER_CD                           877
Sales order line number               586
Stock class                             2
Consider count hodiday Saturday         4
SO QTY                                337
OTHER AREA SHIP DIV                     2
ALLOCATION QTY                        337
SUPPLIER INV AMOUNT                 25953
PACKING RANK                            7
PRODUCT_CD                         302479
PRODUCT ATTRIBUTION                     2
SPECIAL DIV                             2
LOGICAL PLANT                           3
PURCHASE AMOUNT                     26078
VSD                                   371
DIRECT SHIP FLG                         2
DELI_DIV                               10
label                                   2
Ship Mode                              20
SHIP DECISION NO                   249902
PACK QTY                              125
WEIGHT PER PIECE                     8395
SUPPLIER_DIV                            4
HEAVY_FLG                               2
EXPENSIVE_FLG                           2
SPECIAL_DIV                             2
ACTUAL_SHIP_DAYS                      308
SPECIFY_PRODUCTION_DAYS                57
SPECIFY_SHIP_DAYS                      79
HAZARD_FLG                              1
SO_DAY_OF_MONTH                        31
SO_DAY_OF_WEEK                          6
IO_UNFIT_FLG                            2
WEIGHT_UNIT                             1
REASON_CD                              61
SOUF_RCV_NO                         14819
QTUF_RCV_NO                           588
SO_TIME                             42778
SUPPLIER_CATEGORY_CD                    5
PRODUCT_ASSORT                          1
dtype: int64

In [13]:
handle_whitespace(df_4_6, "April to June")

Whitespace in April to June:

/home/huyy-giaa/Develop/DS108_TH/Lab_4/src/cleaning_process.py:58: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

,Order date,SUBSIDIARY_CD,GLOBAL_NO,CLASSIFY_CD,CUST_CD,BRAND_CD,INNER_CD,SUPPLIER_CD,Sales order line number,Stock class,...,SO_DAY_OF_MONTH,SO_DAY_OF_WEEK,IO_UNFIT_FLG,WEIGHT_UNIT,REASON_CD,SOUF_RCV_NO,QTUF_RCV_NO,SO_TIME,SUPPLIER_CATEGORY_CD,PRODUCT_ASSORT
0,2022-04-04 00:00:00,MJP,1000074430653,21034701,74,HAK1,F7371210001,8107,1,1,...,4,1,0,g,401,805169,NaN,120324,5,NaN
1,2022-04-26 00:00:00,MJP,5004180038393,23028764,4180,S3M1,K9045010089,8484,1,1,...,26,2,0,g,455,NaN,NaN,171618,5,NaN
2,2022-04-19 00:00:00,MJP,1000074434232,21059031,74,THT1,F5109250104,8233,1,1,...,19,2,0,g,451,864727,NaN,184619,5,NaN
3,2022-04-22 00:00:00,MJP,1000074434911,3731227,74,MSM1,79014275005,3013,1,1,...,22,5,0,g,410,NaN,NaN,93246,5,NaN
4,2022-04-22 00:00:00,MJP,1000074435036,3954111,74,MSM1,30357450001,3081,1,1,...,22,5,0,g,410,NaN,NaN,153401,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399048,2022-06-21 00:00:00,MJP,12723881903882,3643112,723881,MSM1,30161190001,0143,2,1,...,21,2,0,g,NaN,NaN,NaN,142414,5,NaN
399049,2022-05-20 00:00:00,MJP,12064048003310,3632307,64048,MSM1,30076110001,3763,53,1,...,20,5,0,g,NaN,NaN,NaN,170033,3,NaN
399050,2022-04-07 00:00:00,MJP,11285461432934,2042002,285461,MSM1,20071220008,0214,2,1,...,7,4,0,g,NaN,NaN,NaN,170410,5,NaN
399051,2022-04-14 00:00:00,MJP,13520529104003,3733118,520529,MSM1,30176020762,3132,2,1,...,14,4,0,g,NaN,NaN,NaN,92222,5,NaN
399052,2022-05-31 00:00:00,MJP,12167240910957,5010009,167240,MSM1,53036592866,4017,1,1,...,31,2,0,g,NaN,NaN,NaN,111102,5,NaN

### DROP USELESS COLUMNS IN DATASET APRIL TO JUNE

In [14]:
drop_columns(df_4_6, "April to June")
drop_duplicate_columns(df_4_6)
# Drop the columns that are not needed for EDA and modeling 
# (because they only appear when the order is shiped)
df_4_6.drop(columns=['ACTUAL_SHIP_DAYS', 'REASON_CD'], errors='ignore', inplace=True)

Missing values in April to June:
Order date                              0
SUBSIDIARY_CD                           0
GLOBAL_NO                               0
CLASSIFY_CD                             0
CUST_CD                                 0
BRAND_CD                                0
INNER_CD                                0
SUPPLIER_CD                             0
Sales order line number                 0
Stock class                             0
Consider count hodiday Saturday         0
SO QTY                                  0
OTHER AREA SHIP DIV                333402
ALLOCATION QTY                          0
SUPPLIER INV AMOUNT                     0
PACKING RANK                            0
PRODUCT_CD                              0
PRODUCT ATTRIBUTION                     0
SPECIAL DIV                             0
LOGICAL PLANT                           0
PURCHASE AMOUNT                         0
VSD                                     0
DIRECT SHIP FLG                         0
DELI_DIV                                0
label                                   0
Ship Mode                            6588
SHIP DECISION NO                    33317
PACK QTY                                0
WEIGHT PER PIECE                        0
SUPPLIER_DIV                            4
HEAVY_FLG                               0
EXPENSIVE_FLG                           0
SPECIAL_DIV                             0
ACTUAL_SHIP_DAYS                        0
SPECIFY_PRODUCTION_DAYS                 0
SPECIFY_SHIP_DAYS                       0
HAZARD_FLG                              0
SO_DAY_OF_MONTH                         0
SO_DAY_OF_WEEK                          0
IO_UNFIT_FLG                            0
WEIGHT_UNIT                          1877
REASON_CD                          378842
SOUF_RCV_NO                        384211
QTUF_RCV_NO                        398460
SO_TIME                                 0
SUPPLIER_CATEGORY_CD                    0
PRODUCT_ASSORT                     399053
dtype: int64
Column 'SUBSIDIARY_CD' has only one unique value. Consider dropping this column.
Column 'GLOBAL_NO' has 399053 unique values, which is more than 90% of the total rows. Consider dropping this column.
Column 'OTHER AREA SHIP DIV' has 83.55% missing values. Consider dropping this column.
Column 'HAZARD_FLG' has only one unique value. Consider dropping this column.
Column 'WEIGHT_UNIT' has only one unique value. Consider dropping this column.
Column 'REASON_CD' has 94.94% missing values. Consider dropping this column.
Column 'SOUF_RCV_NO' has 96.28% missing values. Consider dropping this column.
Column 'QTUF_RCV_NO' has 99.85% missing values. Consider dropping this column.
Column 'PRODUCT_ASSORT' has 100.00% missing values. Consider dropping this column.
No duplicate columns found.

### DATA UNIFICATION FOR DATASET JULY TO SEPTEMBER

In [15]:
check_same_dtypes(delay_7_9, not_delay_7_9)

They are the same

In [16]:
check_columns_name(delay_7_9, not_delay_7_9)

They have the same column names

In [17]:
df_7_9 = concat_df(delay_7_9, not_delay_7_9)

### OVERVIEW OF DATASET APRIL TO JUNE

In [18]:
overview_dataset(df_7_9, "July to September")

Overview of July to September:
Dataset shape: (1074897, 37)
Number of columns: 37
Number of rows: 1074897
Data overview of data July to September:,         Order date SUBSIDIARY_CD       GLOBAL_NO   CLASSIFY_CD       CUST_CD  \
count      1074897       1074897         1074897  1.074897e+06  1.074897e+06
unique          79             1         1074897           NaN           NaN
top     2022-07-01           MJP  05750023003736           NaN           NaN
freq         20432       1074897               1           NaN           NaN
mean           NaN           NaN             NaN  6.032145e+06  2.442852e+05
std            NaN           NaN             NaN  6.378738e+06  2.461140e+05
min            NaN           NaN             NaN  1.030101e+06  1.000000e+01
25%            NaN           NaN             NaN  3.637001e+06  6.159700e+04
50%            NaN           NaN             NaN  3.738001e+06  1.320860e+05
75%            NaN           NaN             NaN  3.954111e+06  4.069320e+05
max            NaN           NaN             NaN  9.901000e+07  9.999130e+05

       BRAND_CD     INNER_CD SUPPLIER_CD  Sales order line number  \
count   1074897      1074897     1074897             1.074897e+06
unique     2014       214841         932                      NaN
top        MSM1  30350820001        0143                      NaN
freq     937736        26724       94968                      NaN
mean        NaN          NaN         NaN             1.546860e+02
std         NaN          NaN         NaN             3.356841e+03
min         NaN          NaN         NaN             1.000000e+00
25%         NaN          NaN         NaN             1.000000e+00
50%         NaN          NaN         NaN             3.000000e+00
75%         NaN          NaN         NaN             1.200000e+01
max         NaN          NaN         NaN             9.005000e+04

         Stock class  ...      PACK QTY  WEIGHT PER PIECE  SUPPLIER_DIV  \
count   1.074897e+06  ...  1.074897e+06      1.074897e+06  1.074889e+06
unique           NaN  ...           NaN               NaN           NaN
top              NaN  ...           NaN               NaN           NaN
freq             NaN  ...           NaN               NaN           NaN
mean    9.926951e-01  ...  3.487939e+00      8.272667e+02  1.293824e+00
std     8.515592e-02  ...  1.237256e+02      5.866777e+03  6.737283e-01
min     0.000000e+00  ...  0.000000e+00      0.000000e+00  1.000000e+00
25%     1.000000e+00  ...  0.000000e+00      1.600000e+01  1.000000e+00
50%     1.000000e+00  ...  0.000000e+00      1.000000e+02  1.000000e+00
75%     1.000000e+00  ...  0.000000e+00      4.500000e+02  1.000000e+00
max     1.000000e+00  ...  2.500000e+04      1.300000e+06  4.000000e+00

         SPECIAL_DIV  SO_DAY_OF_MONTH SO_DAY_OF_WEEK     REASON_CD  \
count   1.074897e+06     1.074897e+06   1.074897e+06  41883.000000
unique           NaN              NaN            NaN           NaN
top              NaN              NaN            NaN           NaN
freq             NaN              NaN            NaN           NaN
mean    2.421255e-02     1.534687e+01   3.157167e+00    390.682067
std     1.537086e-01     9.132382e+00   1.464731e+00    124.006981
min     0.000000e+00     1.000000e+00   1.000000e+00    101.000000
25%     0.000000e+00     7.000000e+00   2.000000e+00    398.000000
50%     0.000000e+00     1.500000e+01   3.000000e+00    410.000000
75%     0.000000e+00     2.300000e+01   4.000000e+00    410.000000
max     1.000000e+00     3.100000e+01   6.000000e+00    999.000000

        SOUF_RCV_NO    QTUF_RCV_NO       SO_TIME
count         36491    1345.000000  1.074897e+06
unique        36382            NaN           NaN
top          195164            NaN           NaN
freq              5            NaN           NaN
mean            NaN  239033.719703  1.345315e+05
std             NaN   85643.202894  3.220171e+04
min             NaN   35444.000000  1.040700e+04
25%             NaN  166036.000000  1.053230e+05
50%             NaN  233374.000000  1.358350e+05
75%             NaN  307519.000000  1.621410e+05
max             NaN  939659.000000  2.030000e+05

[11 rows x 37 columns]

In [19]:
check_data_types(df_7_9, "July to September")

Data types in July to September:
Order date                          object
SUBSIDIARY_CD                       object
GLOBAL_NO                           object
CLASSIFY_CD                          int64
CUST_CD                              int64
BRAND_CD                            object
INNER_CD                            object
SUPPLIER_CD                         object
Sales order line number              int64
Stock class                          int64
Consider count hodiday Saturday      int64
SO QTY                               int64
OTHER AREA SHIP DIV                float64
ALLOCATION QTY                       int64
SUPPLIER INV AMOUNT                float64
PACKING RANK                        object
PRODUCT_CD                          object
PRODUCT ATTRIBUTION                  int64
SPECIAL DIV                          int64
LOGICAL PLANT                        int64
PURCHASE AMOUNT                    float64
VSD                                 object
DIRECT SHIP FLG                      int64
DELI_DIV                            object
label                                int64
Ship Mode                           object
SHIP DECISION NO                   float64
PACK QTY                             int64
WEIGHT PER PIECE                     int64
SUPPLIER_DIV                       float64
SPECIAL_DIV                          int64
SO_DAY_OF_MONTH                      int64
SO_DAY_OF_WEEK                       int64
REASON_CD                          float64
SOUF_RCV_NO                         object
QTUF_RCV_NO                        float64
SO_TIME                              int64
dtype: object

In [20]:
check_unique_values(df_7_9, "July to September")

Unique values in July to September:
Order date                              79
SUBSIDIARY_CD                            1
GLOBAL_NO                          1074897
CLASSIFY_CD                           5035
CUST_CD                              51456
BRAND_CD                              2014
INNER_CD                            214841
SUPPLIER_CD                            932
Sales order line number               3955
Stock class                              2
Consider count hodiday Saturday          4
SO QTY                                 685
OTHER AREA SHIP DIV                      1
ALLOCATION QTY                         685
SUPPLIER INV AMOUNT                  40843
PACKING RANK                             7
PRODUCT_CD                          717622
PRODUCT ATTRIBUTION                      2
SPECIAL DIV                              2
LOGICAL PLANT                            3
PURCHASE AMOUNT                      41099
VSD                                    382
DIRECT SHIP FLG                          2
DELI_DIV                                10
label                                    2
Ship Mode                               20
SHIP DECISION NO                    460324
PACK QTY                               177
WEIGHT PER PIECE                     11632
SUPPLIER_DIV                             4
SPECIAL_DIV                              2
SO_DAY_OF_MONTH                         31
SO_DAY_OF_WEEK                           6
REASON_CD                               66
SOUF_RCV_NO                          36382
QTUF_RCV_NO                           1308
SO_TIME                              46173
dtype: int64

In [21]:
handle_whitespace(df_7_9, "July to September")

Whitespace in July to September:

,Order date,SUBSIDIARY_CD,GLOBAL_NO,CLASSIFY_CD,CUST_CD,BRAND_CD,INNER_CD,SUPPLIER_CD,Sales order line number,Stock class,...,PACK QTY,WEIGHT PER PIECE,SUPPLIER_DIV,SPECIAL_DIV,SO_DAY_OF_MONTH,SO_DAY_OF_WEEK,REASON_CD,SOUF_RCV_NO,QTUF_RCV_NO,SO_TIME
0,2022-08-25,MJP,08344472000137,21031103,344472,OSA1,F7171260007,8121,8,1,...,0,1020,2.0,0,25,4,453.0,NaN,NaN,135557
1,2022-08-12,MJP,06000641365551,3712333,641,MSM1,30071630003,0263,1,1,...,0,120,1.0,0,12,5,451.0,NaN,NaN,134532
2,2022-07-08,MJP,07032167936864,21045918,32167,SMC1,F7499483132,9102,1,1,...,0,18000,3.0,0,8,5,410.0,NaN,NaN,160936
3,2022-07-08,MJP,01710046000973,21058302,710046,MIB1,F4524160001,9163,1,1,...,0,500,2.0,0,8,5,453.0,NaN,NaN,160702
4,2022-08-25,MJP,07107539916817,21050569,107539,NIQ1,F3017310155,9176,6,1,...,0,36,2.0,0,25,4,455.0,NaN,NaN,160244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074892,2022-07-06,MJP,04119083533938,3954109,119083,MSM1,30350840002,3081,37,1,...,0,10500,1.0,0,6,3,NaN,NaN,NaN,171036
1074893,2022-09-30,MJP,07169222913959,3954111,169222,MSM1,30357250002,3212,9,1,...,0,648,1.0,0,30,5,NaN,NaN,NaN,134543
1074894,2022-07-29,MJP,GC00EDMR000719,3743528,251577,MSM1,30220350001,0229,4,1,...,0,33,1.0,0,29,5,NaN,NaN,NaN,182313
1074895,2022-08-23,MJP,07108386964458,21055001,108386,SA11,F5201400207,8106,5,1,...,0,2,3.0,0,23,2,NaN,NaN,NaN,133324
1074896,2022-08-03,MJP,05750023003736,3954109,750023,MSM1,30350840001,3081,59,1,...,0,1246,1.0,0,3,3,NaN,NaN,NaN,113735

In [22]:
drop_columns(df_7_9, "April to June")
drop_duplicate_columns(df_7_9)
# Drop the columns that are not needed for EDA and modeling 
# (because they only appear when the order is shiped)
df_7_9.drop(columns=['ACTUAL_SHIP_DAYS', 'REASON_CD'], errors='ignore', inplace=True)

Missing values in April to June:
Order date                               0
SUBSIDIARY_CD                            0
GLOBAL_NO                                0
CLASSIFY_CD                              0
CUST_CD                                  0
BRAND_CD                                 0
INNER_CD                                 0
SUPPLIER_CD                              0
Sales order line number                  0
Stock class                              0
Consider count hodiday Saturday          0
SO QTY                                   0
OTHER AREA SHIP DIV                 912254
ALLOCATION QTY                           0
SUPPLIER INV AMOUNT                      0
PACKING RANK                             0
PRODUCT_CD                               0
PRODUCT ATTRIBUTION                      0
SPECIAL DIV                              0
LOGICAL PLANT                            0
PURCHASE AMOUNT                          0
VSD                                      0
DIRECT SHIP FLG                          0
DELI_DIV                                 0
label                                    0
Ship Mode                            14492
SHIP DECISION NO                     71414
PACK QTY                                 0
WEIGHT PER PIECE                         0
SUPPLIER_DIV                             8
SPECIAL_DIV                              0
SO_DAY_OF_MONTH                          0
SO_DAY_OF_WEEK                           0
REASON_CD                          1033014
SOUF_RCV_NO                        1038406
QTUF_RCV_NO                        1073552
SO_TIME                                  0
dtype: int64
Column 'SUBSIDIARY_CD' has only one unique value. Consider dropping this column.
Column 'GLOBAL_NO' has 1074897 unique values, which is more than 90% of the total rows. Consider dropping this column.
Column 'OTHER AREA SHIP DIV' has 84.87% missing values. Consider dropping this column.
Column 'REASON_CD' has 96.10% missing values. Consider dropping this column.
Column 'SOUF_RCV_NO' has 96.61% missing values. Consider dropping this column.
Column 'QTUF_RCV_NO' has 99.87% missing values. Consider dropping this column.
No duplicate columns found.

In [23]:
df_4_6['Order date'] = pd.to_datetime(df_4_6['Order date'], errors='coerce')
df_7_9['Order date'] = pd.to_datetime(df_7_9['Order date'], errors='coerce')
df_4_6['VSD'] = pd.to_datetime(df_4_6['VSD'], errors='coerce')
df_7_9['VSD'] = pd.to_datetime(df_7_9['VSD'], errors='coerce')

In [24]:
df_4_6['Order date'].head()

0   2022-04-04
1   2022-04-26
2   2022-04-19
3   2022-04-22
4   2022-04-22
Name: Order date, dtype: datetime64[ns]

In [25]:
df_7_9['Order date'].head()

0   2022-08-25
1   2022-08-12
2   2022-07-08
3   2022-07-08
4   2022-08-25
Name: Order date, dtype: datetime64[ns]

### EXPORT DATA

In [26]:
current_dir = Path.cwd()
path_df_4_6 = current_dir / '..' / 'data' / 'tidy' / 'tidy_dataset_4_6.csv'
path_df_7_9 = current_dir / '..' / 'data' / 'tidy' / 'tidy_dataset_7_9.csv'

if not path_df_4_6.exists():
    export_data(df_4_6, "../data/tidy/tidy_dataset_4_6.csv")
else:
    print("This file already exists: ", path_df_4_6)
    
if not path_df_7_9.exists():
    export_data(df_7_9, "../data/tidy/tidy_dataset_7_9.csv")
else:
    print("This file already exists: ", path_df_7_9)